name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodbtest:
        image: mongo:4.4
        ports:
          - "27017:27017"
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Ajuste a versão do Node.js conforme necessário

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB..."
          RETRY_COUNT=0
          MAX_RETRIES=30
          until docker exec mongodbtest mongosh --eval 'db.runCommand({ connectionStatus: 1 })' --quiet; do
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "MongoDB did not become ready in time."
              exit 1
            fi
            echo "Still waiting for MongoDB... ($RETRY_COUNT/$MAX_RETRIES)"
            sleep 5
          done
          echo "MongoDB is ready to accept connections."

      - name: Run tests and generate coverage
        run: npm install && npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}